[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Low level IO"
edition = "2018"
name = "llio"
version = "0.1.0"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
log = "0.4.14"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}
susres = {path = "../susres"}

# RTC dependencies
bitflags = "1.2.1"
locales = {path = "../../locales"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]
chrono = "0.4.19"

[dev-dependencies]
"chrono" = "0.4.19"
"rand" = "0.8.5"

[features]
debugprint = []
wfi_off = [] # useful for serial port debugging, forces power on so the UART characters can finish printing
tts = []
default = [] # "debugprint"
#default = ["debugprint"] # , "fccagent"
