[workspace]
default-members = [
  "services/log-server",
  "services/graphics-server",
  "services/ticktimer-server",
  "services/xous-names",
  "services/keyboard",
  "services/com",
  "services/trng",
  "services/gam",
  "services/status",
  "imports/com_rs-ref",
  "services/ime-plugin-api",
  "services/benchmark",
  "services/benchmark-target",
  "services/ime-frontend",
  "services/ime-plugin-shell",
  "services/content-plugin-api",
  "services/shellchat",
  "services/llio",
  "services/cb-test-srv",
  "services/cb-test-c1",
  "services/cb-test-c2",
  "services/susres",
  "services/codec",
  "services/engine-sha512",
  "services/engine-25519",
  "services/aes",
  "services/test-stub",
  "services/spinor",
  "services/root-keys",
  "services/jtag",
  "services/test-stub2",
  "services/pddb",
  "services/net",
  "services/dns",
  "services/modals",
  "apps/ball",
  "apps/repl",
  "services/espeak",
]
members = [
  "xous-ipc",
  "xous-rs",
  "tools",
  "macros",
  "services/aes-test",
  "services/graphics-server",
  "services/log-server",
  "services/ticktimer-server",
  "services/com",
  "services/xous-names",
  "services/keyboard",
  "services/kernel-test",
  "services/trng",
  "services/gam",
  "services/status",
  "services/benchmark",
  "services/benchmark-target",
  "services/ime-frontend",
  "services/ime-plugin-shell",
  "services/rkyv-test-server",
  "services/rkyv-test-client",
  "services/shellchat",
  "svd2repl",
  "svd2utra",
  "xtask",
  "imports/com_rs-ref",
  "services/ime-plugin-api",
  "services/content-plugin-api",
  "services/llio",
  "services/cb-test-srv",
  "services/cb-test-c1",
  "services/cb-test-c2",
  "services/susres",
  "services/codec",
  "services/engine-sha512",
  "services/engine-25519",
  "services/aes",
  "services/test-stub",
  "services/spinor",
  "services/root-keys",
  "services/jtag",
  "tools/wycheproof-import",
  "services/test-stub2",
  "services/pddb",
  "services/net",
  "services/dns",
  "services/modals",
  "apps/ball",
  "apps/repl",
  "kernel",
  "services/espeak",
]
resolver = "2"

# These packages have custom RUSTFLAGS, so if they
# were included in the workspace they would cause
# packages to be rebuilt every time they were touched.
# Keep them out of the main workspace.
exclude = [
  "loader",
  "utralib",  # Exclude UTRA, since it is machine-generated.
  "locales",  # exclude because it is machine-generated
]

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = "fat"
incremental = true
#panic = "abort" # Remove panic output, which can reduce file size
#opt-level = 'z'  # Optimize for size instead of performance

[patch.crates-io]
xous = {path = "xous-rs"}
xous-macros = {path = "macros"}

# prefer hardware-accelerated versions of services
[patch.crates-io.sha2]
path = "services/engine-sha512"
[patch.crates-io.aes]
path = "services/aes"

[patch.crates-io.curve25519-dalek]
git="https://github.com/betrusted-io/curve25519-dalek.git"
branch="main"
#path = "../curve25519-dalek"  # when doing local dev work
# feature overrides are specified at the crate level

[patch."https://github.com/betrusted-io/xous-engine-25519.git"]
engine-25519 = {path = "services/engine-25519"}