[package]
name = "modals"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Ux modals server"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous-ipc = { path = "../../xous-ipc" }
rkyv = {version = "0.4.3", features = ["const_generics"], default-features = false}
gam = {path="../gam"}
trng = {path="../trng"}
tts-frontend = {path="../tts"}
locales = {path = "../../locales"}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
ux_tests = []
tts = []
default = []
