[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Status bar for Xous"
edition = "2018"
name = "status"
version = "0.1.0"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
com = {path = "../com"}
content-plugin-api = {path = "../content-plugin-api"}
log = "0.4.14"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
trng = {path = "../trng"}
llio = {path = "../llio"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}
graphics-server = {path = "../graphics-server"}
gam = {path = "../gam"}
locales = {path = "../../locales"}
susres = {path = "../susres"}
root-keys = {path = "../root-keys"}
modals = {path = "../modals"}
pddb = {path = "../pddb"}
net = {path = "../net"}
keyboard = {path = "../keyboard"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

# short circuit the datetime call on hosted mode
[target.'cfg(any(windows,unix))'.dependencies]
chrono = "0.4"

[features]
debugprint = []
braille = [] # used for braille mode, so console isn't overwhelmed with status
tts = []
# default = ["debugprint"] # "debugprint"
default = []
