[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Graphical Abstraction Manager for Xous"
edition = "2018"
name = "gam"
version = "0.1.0"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
com = {path = "../com"} # used by the backlight setting on the main menu thread
content-plugin-api = {path = "../content-plugin-api"}
graphics-server = {path = "../graphics-server"}
ime-plugin-api = {path = "../ime-plugin-api"}
ime-plugin-shell = {path = "../ime-plugin-shell"}
keyboard = {path = "../keyboard"}
log = "0.4.14"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
trng = {path = "../trng"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

susres = {path = "../susres"} # used for the sleep now menu item

enum_dispatch = "0.3.7" # used for trait-based dispatch off of multiple layout objects.
locales = {path = "../../locales"}

tts-frontend = {path="../tts"}

qrcode = { version = "0.12", default-features = false }

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
tts = []
# default = ["debugprint"] # "debugprint"
default = []
