[package]
name = "loader"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Initial kernel loader for Xous"

[dependencies]
ed25519-dalek-loader = { path = "ed25519-dalek-loader", default-features = false }
curve25519-dalek-loader = { path = "curve25519-dalek-loader", default-features = false, features = ["u32e_backend"] }

[target.'cfg(not(any(windows, unix)))'.dependencies]
utralib = { path = "../utralib", default_features = false }

[dependencies.com_rs]
git = "https://github.com/betrusted-io/com_rs"
branch = "main"

[dev-dependencies]
lazy_static = "1.4.0"

[features]
debug-print = []
earlyprintk = []
renode-bypass = []
#default = ["debug-print"]
default = []