[package]
name = "sha2-loader"
version = "0.9.5"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "sha2 hardware accelerator engine"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]

# Rust-standard digest API dependencies
digest = "0.9.0"
block-buffer = "0.9.0"
opaque-debug = "0.3.0" # prevents internal hash state leakage from debug structures

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
default = []
