[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "A shell with a chat-like interface"
edition = "2018"
name = "shellchat"
version = "0.1.0"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
com = {path = "../com"}
content-plugin-api = {path = "../content-plugin-api"}# all content canvas providers must provide this API
gam = {path = "../gam"}
graphics-server = {path = "../graphics-server"}
ime-plugin-api = {path = "../ime-plugin-api"}
ime-plugin-shell = {path = "../ime-plugin-shell"}
ime-plugin-tts = {path = "../ime-plugin-tts"}
llio = {path = "../llio"}
log = "0.4.14"
log-server = {path = "../log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
xous-ipc = {path = "../../xous-ipc"}
xous-names = {path = "../xous-names"}
keyboard = {path = "../keyboard"}
susres = {path = "../susres"}
codec = {path = "../codec"}
#engine-sha512 = {path="../engine-sha512"}
sha2 = {path="../engine-sha512"}
digest = "0.9.0"
aes={path="../aes"}
cipher = "0.3.0"
engine-25519 = {path="../engine-25519"}
spinor = {path="../spinor"}
root-keys = {path="../root-keys"}
jtag = {path="../jtag"}
net = {path="../net"}
dns = {path="../dns"}
pddb = {path="../pddb"}
modals = {path="../modals"}

tts-frontend = {path="../tts"}
locales = {path = "../../locales"}

trng = {path = "../trng"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

chrono = {version = "0.4.19", default-features = false, features = ["std"]}

# for audio self-test analysis
spectrum-analyzer = "0.5.2"
# used to parse net connectivity results
com_rs-ref = {path = "../../imports/com_rs-ref"}

# for the curve25519 tests
# hardware acceleration adaptations are inserted into a fork of the main branch.
rand_core = "0.5.1"
hex = {version = "0.4.3", default-features = false, features = []}
#sha2 = {version = "0.9.5", default-features = false, features = []}
[dependencies.curve25519-dalek]
version = "3.1.0" # note this is patched to our fork in ./Cargo.toml
default-features = false
features = ["u32_backend", "betrusted"]

[dependencies.x25519-dalek]
version = "1.1.1"
default-features = false
features = ["u32_backend"]

[dependencies.ed25519-dalek]
version = "1.0.1"
#path = "../../../ed25519-dalek"
default-features = false
features = ["u32_backend", "rand"]

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
spinortest = [] # for spinor testing. contra-indicated with PDDB, as it steals memory from the PDDB.
benchmarks = [] # adds the benchmark routines. Left off normally to free up code and memory space.
tts = [] # adds text to speech plugin
pddbtest = []
default = [] # "debugprint"

[target.'cfg(any(windows,unix))'.dependencies]
debug-here = "*"
